export const theme = {
  primaryDark: '#2B2C2F',
  primaryLight: '#2B83CD',
  deleteColor: '#E20E0E',
  deleteHover: '#FF5555',
  colorWhite: '#FFFFFF',
  primaryHover: '#343078',
  hoverMenuItem: '#7FB4E1',
  mobileL: '900px',
  mobile: '767px',
  mobileS: '319px',
  mobileXS: '250px',
  mobileM: '666px',
  menuItemsMax: '700px',
  profileButtonMax: '1050px',
  companyFont: '"Trebuchet MS", Helvetica, sans-serif',
  menuFont: '"Trebuchet MS", Helvetica, sans-serif',
  profileFont: '"Trebuchet MS", Helvetica, sans-serif',
  mainFont: '"Trebuchet MS", Helvetica, sans-serif'
}
